(source gnu)
(source melpa)
(source "marmalade" "http://marmalade-repo.org/packages/")
(source "org" "http://orgmode.org/elpa/")

(depends-on "auto-complete")
(depends-on "dash")
(depends-on "f")
(depends-on "flycheck")
(depends-on "helm")
(depends-on "magit")
(depends-on "popup")
(depends-on "projectile")
(depends-on "s")
(depends-on "smartparens")
(depends-on "yasnippet")
(depends-on "color-theme-solarized")
(depends-on "haskell-mode")
(depends-on "exec-path-from-shell")
(depends-on "haskell-mode")
(depends-on "restclient")
(depends-on "cmake-mode")
(depends-on "cmake-project")

(depends-on "pallet")
